// =====================================================================
// REFINERY QUEST - Chapter Data (extracted from Leffler's textbook)
// Each chapter: 4-8 concepts with full detail, 4-6 quiz questions
// =====================================================================

const chapters = [
// ===================== CHAPTER I =====================
{id:1,n:"I",t:"Introduction",d:"How the book is structured and what matters most",
concepts:[
{t:"Three Ways to Use This Book",h:"Reference, textbook, or self-study guide",
b:"The book serves three purposes: (1) a reference book with a detailed index and table of contents, (2) a textbook for courses on refining with problems to solve, and (3) a personal self-study guide. The author designed it primarily for self-study, adding humor and practical examples to make the dry material more digestible.",
x:"Leffler recommends finding a process engineer to ask questions as you go. The book is meant to raise as many questions as it answers - that's not a bug, it's a feature."},
{t:"The Essential Chapters",h:"Where to focus your attention and what you can skim",
b:"Chapter II (Crude Oil Characteristics) is the foundation - most important. Don't get bogged down by the mechanical details in Chapter III (Distilling). The conversion processes are all important: cat cracking (VI), alkylation (VIII), catalytic reforming (IX), residue reduction (X), and hydrocracking (XI). Chapter XIX (Simple & Complex Refineries) ties everything together - it's the capstone.",
x:"The author calls Chapters XIII-XVIII, XX, and XXI 'lagniappe' - a Cajun word meaning a small gift a merchant gives a customer. These chapters are useful but not vital."},
{t:"The Gasoline Blending Chapter is Fun",h:"It connects refining to something you already know: car engines",
b:"Chapter XII on gasoline blending deals with something familiar yet mysterious - how car engines work, why gasoline has different grades, and what octane numbers actually mean. The chapter on gas plants (VII) is less critical to understand in depth - the mechanics are important to operators but less so for general understanding.",
x:"The difference between a simple refinery and a complex one is exactly the add-on units discussed in Chapters III through XVII. Once you understand each unit individually, Chapter XIX shows how they all fit together like pieces of a puzzle."}
],
quiz:[
{q:"According to Leffler, which chapter is the most important in the entire book?",o:["Chapter I - Introduction","Chapter II - Crude Oil Characteristics","Chapter XII - Gasoline Blending","Chapter XIX - Simple & Complex Refineries"],c:1,e:"Leffler explicitly says 'Chapter II on crude is most important' - it's the foundation that everything else builds on."},
{q:"What is 'lagniappe'?",o:["A refining process for heavy crude","A Cajun word meaning a small bonus gift","A type of catalyst used in reforming","The French word for distillation"],c:1,e:"Lagniappe is a Cajun word meaning a small gift a merchant gives a customer. Leffler uses it to describe the bonus chapters that are useful but not essential."},
{q:"Which chapter ties all the refinery processes together?",o:["Chapter II - Crude Oil","Chapter VI - Cat Cracking","Chapter XII - Gasoline Blending","Chapter XIX - Simple & Complex Refineries"],c:3,e:"Chapter XIX shows how all the individual processing units fit together by comparing simple vs. complex refinery configurations."},
{q:"What should you NOT worry about getting bogged down in?",o:["Crude oil chemistry","Mechanical details of distilling (Ch III)","Cat cracking yields","Gasoline octane numbers"],c:1,e:"Leffler specifically warns not to let Chapter III's mechanical detail about distilling dismay you - the fundamental concepts matter more than the mechanical specifics."}
]},

// ===================== CHAPTER II =====================
{id:2,n:"II",t:"Crude Oil Characteristics",d:"What crude oil actually IS - the foundation of everything in refining",
concepts:[
{t:"Crude Oil Is NOT a Chemical Compound",h:"Water boils at exactly 212°F. Crude oil? It's thousands of different boiling points.",
b:"The most important thing about crude oil is what it is NOT. It is not a chemical compound like water (H2O). It is a mixture of thousands of different hydrocarbon compounds, from molecules as simple as CH4 (methane) to ones as complex as C55H60. Each compound has its own unique boiling temperature. When you heat crude, it doesn't all boil at one temperature - compounds boil off progressively as temperature rises.",
x:"Contrast this with water: heat water to 212°F and it all boils at that temperature. A thermometer in the pot stays at 212°F until the last drop evaporates. Crude oil behaves completely differently - and this difference is the single most exploited physical property in the entire petroleum industry."},
{t:"Distillation Curves",h:"The refiner's treasure map - every crude has a unique one",
b:"If you heat crude oil step by step and record how much boils off at each temperature, you create a distillation curve. At 150°F, some crude boils off and then stops. Raise it to 450°F, more boils off. At 750°F, even more. Plot temperature on the vertical axis vs. cumulative percent volume evaporated on the horizontal axis, and you get the curve. Each type of crude oil has a unique distillation curve.",
x:"The key insight: generally, the more carbon atoms in a compound, the higher its boiling temperature. Propane (C3H8) boils at -44°F and weighs 4.2 lbs/gallon. Butane (C4H10) boils at 31°F and weighs 4.9 lbs/gallon. Decane (C10H22) boils at 345°F and weighs 6.1 lbs/gallon. Heavier = higher boiling point = denser."},
{t:"Fractions (Cuts)",h:"Slicing the crude oil pie into groups by boiling range",
b:"Refiners group compounds into 'fractions' or 'cuts' - all compounds that boil between two temperatures (called cut points). The standard fractions are: butanes and lighter (below 90°F), gasoline (90-220°F), naphtha (220-315°F), kerosene (315-450°F), gas oil (450-800°F), and residue (800°F and above). Light crudes have more gasoline, naphtha, and kerosene. Heavy crudes have more gas oil and residue.",
x:"There's a direct relationship: heavier compounds have higher boiling temperatures. So the higher the cut points, the heavier the fraction. This is why light crudes are more valuable - they naturally yield more of the lighter, more valuable fractions like gasoline without expensive conversion."},
{t:"Cutting Crudes - Reading the Distillation Curve",h:"How to figure out what's inside any crude oil",
b:"Using a distillation curve, you can calculate exactly how much of each fraction any crude contains. Example: kerosene boils between 315°F and 450°F. Find where 315°F hits the curve (say 26%), find where 450°F hits it (say 42%), and the kerosene content is 42-26 = 16%. You can compare two crudes this way and see which yields more of any product.",
x:"A light crude vs. heavy crude comparison might show: the light crude has 18% kerosene while the heavy has only 16%. The difference is even more dramatic for gasoline - a light crude might yield 25%+ gasoline straight-run, while a heavy crude might only yield 10-15%."},
{t:"API Gravity - Measuring How Heavy or Light a Crude Is",h:"Higher API = lighter crude. Water = 10°API. The formula is diabolical.",
b:"Specific gravity compares a substance's weight to water (water = 1.0). The oil industry uses API gravity, calculated as: °API = 141.5/specific gravity - 131.5. Key relationships: Water = 10°API. Higher API = lighter. Heavy crude = ~18°API (SG 0.95). Light crude = ~36°API (SG 0.84). Gasoline = ~60°API (SG 0.74). Asphalt = ~11°API (SG 0.99).",
x:"A peculiarity: if you mix equal volumes of asphalt (11°API) and naphtha (50°API), the result is NOT 30.5°API. API gravity doesn't average linearly because the formula involves a reciprocal relationship with specific gravity. You have to convert to specific gravity, average those, then convert back."},
{t:"Sweet vs. Sour Crude",h:"Early oilmen literally TASTED crude to check sulfur content",
b:"Crude oils contain varying amounts of sulfur, chemically bonded to hydrocarbon molecules (not easily separated). Sweet crudes have 0.5% sulfur or less; sour crudes have 2.5% or more. The terms come from Pennsylvania oil field days when tasters literally tasted kerosene - sweet taste meant low sulfur (acceptable for lamp oil), sour taste meant too much sulfur (rejected for New York/Philadelphia markets).",
x:"Sulfur is a persistent problem because it's not elemental sulfur floating around - it's chemically bonded into complex hydrocarbon molecules. Removing it requires expensive catalytic processes (hydrotreating). That's why sweet crude commands a premium price."},
{t:"Barrels and Measurement",h:"Why a 'barrel' is 42 gallons, not 50",
b:"Oil was originally shipped in 50-gallon wine barrels from Pennsylvania. To allow for spillage during transport, payment at the destination was for only 42 gallons. The 42-gallon barrel stuck as the US standard. In the US, commerce is in barrels (volume). In Europe, most petroleum was shipped by sea, and the easier measure was weight (tonnes) based on ship displacement.",
x:"This volume vs. weight distinction matters enormously because cracking processes change the density of products. A cat cracker's output weighs the same as its input, but the volume is greater (118% volume yield is typical) because lighter molecules are less dense. Refiners love this 'gain' since products are sold by volume."}
],
quiz:[
{q:"Why doesn't crude oil boil at a single temperature like water does?",o:["It's too heavy to boil","It's a mixture of thousands of compounds, each with its own boiling point","It contains too much sulfur to evaporate","It has been processed already"],c:1,e:"Crude oil is a mixture of thousands of hydrocarbon compounds (CH4 to C55H60), each with its own unique boiling temperature. Water is a single compound (H2O) that boils at exactly 212°F."},
{q:"Propane boils at -44°F and weighs 4.2 lbs/gal. Decane boils at 345°F and weighs 6.1 lbs/gal. What's the general rule?",o:["Lighter compounds have higher boiling points","Heavier compounds boil at lower temperatures","More carbon atoms = higher boiling point = heavier per gallon","Boiling point is unrelated to molecular weight"],c:2,e:"More carbon atoms means a heavier molecule, a higher boiling temperature, and a higher density (lbs/gallon). This relationship is fundamental to all of refining."},
{q:"What is the correct order of crude oil fractions from lightest to heaviest?",o:["Residue, gas oil, kerosene, naphtha, gasoline","Gas oil, kerosene, gasoline, naphtha, residue","Gasoline, naphtha, kerosene, gas oil, residue","Naphtha, gasoline, kerosene, residue, gas oil"],c:2,e:"From lightest to heaviest: butanes & lighter (<90°F) → gasoline (90-220°F) → naphtha (220-315°F) → kerosene (315-450°F) → gas oil (450-800°F) → residue (800°F+)."},
{q:"A crude oil with 36° API gravity has a specific gravity of about 0.84. What does this tell us?",o:["It's a heavy crude with lots of residue","It's a light crude that will yield more gasoline and naphtha","It's very close to water in weight","It has high sulfur content"],c:1,e:"36°API is a light crude (SG 0.84, lighter than water at SG 1.0). Light crudes yield more of the valuable lighter fractions like gasoline, naphtha, and kerosene."},
{q:"Why do 'sweet' crudes command higher prices than 'sour' crudes?",o:["They taste better to quality inspectors","They have less sulfur, meaning lower processing costs to meet environmental specs","They come from more politically stable regions","They are lighter in color"],c:1,e:"Sweet crudes have less sulfur (<0.5%), so refiners spend less on expensive hydrotreating to remove sulfur. The term originally came from tasters in Pennsylvania oil fields who literally tasted kerosene."},
{q:"If a cat cracker's products weigh the same as its feed but the volume is 118%, why?",o:["Extra molecules are created from the air","Cracked (lighter) molecules are less dense, taking up more space per pound","Water is added during cracking","The measurements are wrong"],c:1,e:"Cracking breaks large, dense molecules into smaller, less dense ones. Same total weight but more gallons because lighter molecules take up more space per pound. Products are sold by volume, so refiners love this 'gain.'"}
]},

// ===================== CHAPTER III =====================
{id:3,n:"III",t:"Distilling",d:"The workhorse of the refinery - separating crude into useful fractions in a tall column",
concepts:[
{t:"From Moonshine to 200,000 Barrels a Day",h:"The distilling column is a continuous, industrial-scale version of a moonshiner's still",
b:"A Kentucky moonshiner heats fermented corn mash, vaporizes the alcohol, condenses it, and bottles it. That's simple batch distillation. A second pass through another still gives a cleaner product. But batch processing can't handle 100,000-200,000 barrels/day of crude oil with six different products. The distilling column does this continuously with far less labor, facilities, and energy.",
x:"Think of the distilling column as dozens of moonshiners' stills stacked on top of each other, all running simultaneously and continuously. The liquid flows down while vapor flows up, and separation happens at every level."},
{t:"Inside the Column: Trays, Bubble Caps, and Downcomers",h:"Hot vapor bubbles through liquid on each tray - this is the essence of distilling",
b:"Crude heated to ~750°F enters the column. Over half vaporizes. Inside the column are 30-50 trays with perforations fitted with 'bubble caps.' Hot vapor rising from below is forced to bubble through liquid sitting on each tray. During this bubbling, heat transfers from vapor to liquid - some heavier compounds in the vapor condense into the liquid, while lighter compounds in the liquid vaporize upward. This is the core mechanism.",
x:"The liquid on each tray grows as heavy compounds condense out of the rising vapor. A 'downcomer' lets excess liquid overflow to the next lower tray. Molecules make several round trips: rising as vapor, condensing, then dripping down as liquid. This repeated vapor-liquid scrubbing is what achieves clean separation. One pass wouldn't do it."},
{t:"Side Draws and Product Streams",h:"Tapping the tower at exactly the right heights",
b:"Products are drawn off at different levels of the column. From top to bottom: overhead gases (butane and lighter), straight-run gasoline, naphtha, kerosene, light gas oil, heavy gas oil, and straight-run residue from the very bottom. Each product then goes to its next destination: gases to the gas plant, gasoline to blending, naphtha to the reformer, kerosene to a hydrotreater, light gas oil to fuel blending, heavy gas oil to the cat cracker, and residue to the flasher.",
x:"There's quite a bit of latitude in setting cut points. Moving the naphtha/kerosene cut point from 315°F to 325°F means more naphtha, less kerosene. Interestingly, both cuts get heavier - because the material moving from kerosene to naphtha is heavier than the average naphtha but lighter than the average kerosene."},
{t:"Reflux and Reboil",h:"Sending liquid back down or reheating it to sharpen the cuts",
b:"Refluxing: vapor from the top is cooled and some of the condensed liquid is sent back down the column. This gives the heavy molecules that drifted too high a chance to condense and drop back where they belong. Reboiling: liquid from a lower sidedraw is reheated to drive off any light compounds trapped in it. Both techniques sharpen the separation between adjacent fractions.",
x:"These aren't optional luxuries - without reflux and reboil, separations would be sloppy with large 'tail ends' (overlapping fractions). Refiners also use reflux/reboil to regulate liquid and vapor flows on the trays when crude composition doesn't provide enough natural flow."},
{t:"Cut Points and Tail Ends",h:"Perfect separation is impossible - there's always some overlap",
b:"The temperatures separating adjacent fractions are called cut points. Each fraction has an Initial Boiling Point (IBP) and an End Point (EP). Ideally, the EP of naphtha would equal the IBP of kerosene. In practice, there's overlap - naphtha's EP might be 325°F while kerosene's IBP is 305°F. This overlap is called 'tail ends' and is present in virtually all refining operations.",
x:"The 'effective cut point' is the compromise temperature at which the cuts can be considered cleanly separated. Throughout the industry, when people say 'cut point,' they implicitly mean effective cut point, acknowledging the small overlap."},
{t:"The Furnace - Cooking the Crude Before It Enters",h:"Over half the crude vaporizes before it even hits the column",
b:"The charge pump moves crude from storage through a furnace where it's heated to about 750°F. At this temperature, over half the crude changes to vapor. This hot mixture of liquid and vapor enters the column at the 'flash zone.' Gravity causes the denser liquid to drop toward the bottom while lighter vapors rise through the trays toward the top.",
x:"The furnace is perhaps the most critical single piece of equipment in the refinery. If it goes down, the entire crude unit stops, which affects every downstream unit. Furnace reliability is a constant focus of refinery maintenance teams."}
],
quiz:[
{q:"What is the FIRST processing unit that all crude oil passes through in a refinery?",o:["The cat cracker","The vacuum flasher","The crude distilling unit (CDU)","The reformer"],c:2,e:"Every drop of crude must pass through the CDU first. It's the starting point of all refining - separating crude into its basic fractions before any conversion can happen."},
{q:"The 'essence' of the distilling operation is:",o:["Heating crude in a furnace","Hot vapor bubbling through liquid on each tray, transferring heat","Compressing gases to high pressure","Adding catalysts to break molecules"],c:1,e:"The bubble caps force hot rising vapor to bubble through liquid sitting on each tray. During this contact, heavy compounds condense and light compounds vaporize - this is the core separation mechanism."},
{q:"What are 'tail ends' in distillation?",o:["The residue left at the bottom of the column","The overlap zone where adjacent fractions aren't perfectly separated","The light gases that escape from the top","The heavier crude that enters last"],c:1,e:"Tail ends are the overlapping portions where the end point of one fraction overlaps with the initial boiling point of the next. Perfect separation is impossible - there's always some overlap."},
{q:"If you lower the naphtha/kerosene cut point from 315°F to 305°F, what happens?",o:["More naphtha and more kerosene","Less naphtha and more kerosene","More naphtha and less kerosene","Nothing changes"],c:1,e:"Lowering the cut point means less material goes to naphtha (stops at 305°F) and more goes to kerosene (starts at 305°F). The volumes shift between the two cuts."},
{q:"Why is reflux used in distilling?",o:["To add extra heat to the column","To send condensed liquid back down so heavy molecules that drifted too high can drop back to the right level","To remove sulfur from the products","To speed up the distillation process"],c:1,e:"Reflux sends condensed liquid back down the column, giving heavy molecules that drifted too high another chance to condense and separate properly. Without it, separations would be sloppy."},
{q:"Straight-run heavy gas oil from the distilling column goes to:",o:["Gasoline blending directly","The cat cracker as feed","The reformer","Export sales"],c:1,e:"Heavy gas oil (650-800°F) is sent to the cat cracker where it's broken down into lighter, more valuable products like gasoline."}
]},

// ===================== CHAPTER IV =====================
{id:4,n:"IV",t:"Vacuum Flashing",d:"Using vacuum to separate heavy residue without cracking the molecules",
concepts:[
{t:"The Cracking Problem Above 900°F",h:"Heat heavy molecules too much and they shatter into pieces - more volume than you started with",
b:"When a lab technician heats crude above ~900°F, something strange happens: the cumulative volume recovered exceeds 100%, yet crude is still boiling in the pot. The large hydrocarbon molecules that haven't vaporized are absorbing so much heat energy that they crack into smaller pieces. For example, C16H34 (cetane) cracks into C8H18 (octane) + C6H12 (hexene) + C2H4 (ethylene).",
x:"Why does volume increase? Because smaller molecules take up more room per pound than larger ones. C16H34 weighs 7.2 lb/gal. But the cracked products weigh 5.9, 5.6, and 3.1 lb/gal respectively. Start with 1.00 gallon of C16H34, crack it, and you get 1.38 gallons of products. Same 7.2 lbs, but 38% more volume! Cracking is useful - but only when controlled. The distilling column isn't designed for it."},
{t:"Low Pressure = Lower Boiling Temperatures",h:"The Denver hot dog trick: water boils at 210°F in Denver but 212°F in Houston",
b:"If you sold hot dogs in both Houston (sea level) and Denver (mile high), you'd boil water at 212°F in Houston but only 210°F in Denver. The altitude means thinner air, less atmospheric pressure. The relationship is simple: lower pressure = lower boiling temperature. Heating only helps molecules absorb enough energy to escape the liquid; lower pressure means they need less energy to escape.",
x:"The vacuum flasher exploits this brilliantly. By reducing pressure inside the flasher to 25-40 mmHg (vs 760 mmHg atmospheric), heavy compounds that would normally need 1000-1100°F to boil can be vaporized at only 750°F - well below cracking temperature. Same separation, no cracking damage."},
{t:"The Vacuum Flasher Process",h:"A squat, large-diameter column running under vacuum",
b:"Straight-run residue is pumped directly from the distilling column into the vacuum flasher. Because of how distilling works, the residue enters at a temperature equal to its initial boiling point. A vacuum pump maintains the low pressure inside the flasher. Steam is sometimes injected to further reduce the effective pressure of the hydrocarbons (called steam stripping).",
x:"The vacuum flasher is a squat, large-diameter column - quite different from the tall, narrow distilling column. The large diameter is needed because the low pressure means the vapor occupies a much larger volume than it would at atmospheric pressure."},
{t:"Flasher Products",h:"Light flashed distillate, heavy flashed distillate, and flasher bottoms",
b:"The flasher typically produces: light and heavy flashed distillates (sometimes kept separate for lube oil feed, sometimes combined as 'flasher tops' for cat cracker feed) and flasher bottoms (the heaviest material, used as feed to asphalt plants, thermal crackers, or as residual fuel blending component). Flashing effectively extends the distillation curve to the equivalent of 1000-1100°F.",
x:"The true end point of crude oil is never actually determined. Vacuum distillation doesn't go high enough to vaporize everything. But this doesn't matter - the products from the bottom of the barrel are characterized by gravity and viscosity, not by boiling point. Nobody needs to know exactly where the distillation curve ends."}
],
quiz:[
{q:"When crude is heated above ~900°F, the cumulative volume recovered can exceed 100%. Why?",o:["Extra molecules come from the air","Water contamination expands the volume","Large molecules crack into smaller, less dense pieces that take up more space per pound","The measuring equipment is inaccurate at high temperatures"],c:2,e:"Cracked (smaller) molecules are less dense - they take up more room per pound. 7.2 lbs of C16H34 occupies 1.00 gallon, but when cracked into smaller pieces, the same 7.2 lbs occupies 1.38 gallons."},
{q:"In Denver (altitude 5,280 ft), water boils at approximately:",o:["212°F - same as everywhere","215°F - higher altitude means higher boiling point","210°F - lower pressure means lower boiling point","200°F - much lower due to altitude"],c:2,e:"Lower atmospheric pressure at higher altitude means molecules need less energy to escape the liquid. Water boils at ~210°F in Denver vs 212°F at sea level."},
{q:"The vacuum flasher operates at approximately what pressure?",o:["760 mmHg (atmospheric)","400-500 mmHg","25-40 mmHg","0 mmHg (complete vacuum)"],c:2,e:"The vacuum flasher operates at 25-40 mmHg, compared to 760 mmHg atmospheric pressure. This dramatic pressure reduction allows heavy compounds to boil at much lower temperatures."},
{q:"Flasher bottoms are used for all of the following EXCEPT:",o:["Asphalt plant feed","Thermal cracker feed","Residual fuel blending","Gasoline blending"],c:3,e:"Flasher bottoms are the heaviest material in the refinery - they go to asphalt plants, thermal crackers, or residual fuel. They are far too heavy for gasoline blending."},
{q:"Why is the vacuum flasher shorter and wider than the distilling column?",o:["Aesthetic reasons","Low pressure means vapors take up huge volume, requiring a large diameter","Heavy residue needs a wider base to settle","Building codes require it"],c:1,e:"At very low pressures, vapor occupies much more volume than at atmospheric pressure. The large diameter accommodates this expanded vapor volume."}
]},

// ===================== CHAPTER V =====================
{id:5,n:"V",t:"The Chemistry of Petroleum",d:"Paraffins, olefins, naphthenes, aromatics - the four molecular families you must know",
concepts:[
{t:"Atoms, Valences, and Bonds",h:"Carbon has 4 hands, hydrogen has 1, sulfur has 2, oxygen has 2",
b:"The smallest particle in petroleum chemistry is the atom: carbon (C), hydrogen (H), sulfur (S), oxygen (O). Each element has a specific number of bonds it can form (valence): carbon = 4, hydrogen = 1, sulfur = 2, oxygen = 2. These bonds connect atoms into groups called molecules. All bonds must be satisfied - carbon must always have exactly 4 connections, hydrogen exactly 1.",
x:"Think of carbon as having 4 arms and hydrogen as having 1 arm. Every arm must hold onto something. This simple rule generates thousands of different molecules with vastly different properties. The way atoms connect determines everything: boiling point, density, octane number, reactivity."},
{t:"Paraffins (Alkanes) - The Backbone of Crude Oil",h:"Saturated, straight or branched chains - CnH(2n+2)",
b:"Paraffins are the most common hydrocarbons in crude oil. They have all single bonds (saturated) and follow the formula CnH(2n+2). They can be straight chains (normal paraffins like n-butane, n-hexane) or branched chains (iso-paraffins like isobutane, iso-octane). The 'normal' prefix means straight chain; 'iso' means branched. Branched paraffins have significantly different properties from their straight-chain versions.",
x:"Critical refining fact: straight-chain paraffins are terrible gasoline (low octane, causes knocking) but excellent diesel fuel (high cetane, easy ignition). Branched paraffins are great gasoline (high octane). Same formula, radically different behavior - which is why isomerization and reforming exist."},
{t:"Olefins (Alkenes) - The Reactive Double-Bonders",h:"They have a C=C double bond that makes them chemically aggressive",
b:"Olefins have at least one carbon-carbon double bond, making them 'unsaturated' (not all carbons are fully saturated with hydrogen). Formula: CnH(2n). They are rarely found in crude oil but are created abundantly during cracking. The double bond makes them very reactive - they readily participate in chemical reactions like alkylation and polymerization.",
x:"The double bond is like two people holding both hands together instead of one. It works, but the extra bond can be broken, freeing up bonding capacity for new reactions. This reactivity is what makes olefins valuable feedstocks. Propylene and butylenes from the cat cracker go straight to the alkylation unit."},
{t:"Naphthenes and Aromatics - The Ring Structures",h:"Naphthenes are saturated rings; aromatics have the famous benzene ring with alternating double bonds",
b:"Naphthenes: ring-shaped paraffins with all single bonds (CnH2n). Like a chain that loops around and connects to itself. Aromatics: ring structures with alternating single and double bonds. The simplest is benzene (C6H6) - a ring of 6 carbons. Aromatics are incredibly stable despite their double bonds, have a distinctive smell (hence 'aromatic'), and have very high octane numbers.",
x:"The benzene ring is one of chemistry's most important structures. Toluene is benzene + a methyl group. Xylene is benzene + two methyl groups. These BTX (benzene, toluene, xylene) aromatics are the building blocks of plastics, nylon, polyester, and hundreds of other products. They're worth more as chemicals than as gasoline."},
{t:"Isomers - Same Formula, Completely Different Behavior",h:"n-heptane has 0 octane rating. Iso-octane has 100. Both are just carbon and hydrogen!",
b:"Isomers are compounds with the same chemical formula but different molecular structures. Normal butane and isobutane are both C4H10 but have different boiling points (31°F vs 11°F), different densities, and different uses. The most famous isomer pair: iso-octane (branched C8H18) = 100 octane; n-heptane (straight C7H16) = 0 octane. Same types of atoms, completely opposite engine performance.",
x:"This is why molecular structure matters more than molecular size in refining. Several refinery processes exist purely to change structure without changing size: isomerization (straight → branched), reforming (naphthenes → aromatics), alkylation (combining small olefins with isobutane into branched isoparaffins)."}
],
quiz:[
{q:"Carbon has a valence of 4. This means:",o:["It weighs 4 grams","It forms exactly 4 bonds with other atoms","It has 4 isotopes","It boils at 4°F"],c:1,e:"Valence = number of bonds an atom must form. Carbon always forms exactly 4 bonds. Hydrogen forms 1, oxygen forms 2, sulfur forms 2."},
{q:"Which hydrocarbon family is most common in crude oil?",o:["Olefins","Aromatics","Paraffins","Naphthenes"],c:2,e:"Paraffins (alkanes) are the most abundant hydrocarbons in crude oil. Olefins are rarely found in crude - they're mainly created during cracking."},
{q:"What makes olefins so reactive compared to paraffins?",o:["They contain oxygen","They have a carbon-carbon double bond","They are heavier molecules","They contain sulfur"],c:1,e:"Olefins have at least one C=C double bond. This unsaturated bond can be broken to form new bonds, making olefins reactive feedstocks for processes like alkylation."},
{q:"Iso-octane has an octane rating of 100, while n-heptane has 0. What's the key difference?",o:["Different number of carbon atoms","Different number of hydrogen atoms","Different molecular structure (branched vs. straight chain)","Different amounts of sulfur"],c:2,e:"Both are hydrocarbons with similar sizes, but iso-octane is branched while n-heptane is straight-chain. Branching dramatically resists knocking in engines."},
{q:"PONA stands for:",o:["Pressure, Output, Naphtha, Asphalt","Paraffins, Olefins, Naphthenes, Aromatics","Production, Operations, Networking, Analysis","Pure Organic Nitrogen Analysis"],c:1,e:"PONA describes the four hydrocarbon families: Paraffins (saturated chains), Olefins (double bonds), Naphthenes (saturated rings), Aromatics (benzene rings). PONA analysis tells refiners what's in their feed."},
{q:"Why are aromatics called 'aromatic'?",o:["They're found in aromatic crude oils","They have a distinctive smell","They were discovered in aroma therapy","They produce fragrant smoke when burned"],c:1,e:"Aromatics get their name from their distinctive smell. Benzene, toluene, and xylene all have noticeable odors. The name predates the understanding of their ring structure."}
]},

// ===================== CHAPTER VI =====================
{id:6,n:"VI",t:"Cat Cracking",d:"The refinery's money-maker - converting heavy gas oil into gasoline",
concepts:[
{t:"Why Cat Cracking Was Invented",h:"Too much fuel oil, not enough gasoline - the market demanded a solution",
b:"In the early petroleum industry, consumers wanted more gasoline than crude naturally yielded as a straight-run product. Making enough gasoline from distillation alone would create a glut of heavy fuel oils. Gasoline prices rose while fuel oil prices fell. Process engineers responded by inventing catalytic cracking - the most important conversion process in refining.",
x:"This economic imbalance still drives refining today. The 'natural' yield of gasoline from crude distillation doesn't match market demand. Cat cracking literally reshapes the barrel to match what consumers want to buy."},
{t:"The Catalyst - Like a Troublesome Ten-Year-Old",h:"It causes reactions without being changed itself. Wherever it goes, trouble happens.",
b:"A catalyst facilitates a chemical reaction but comes out unchanged. As Leffler puts it: 'Catalysts are like some ten-year-olds you know. They never get into trouble; it's just that wherever they go, trouble happens.' The cat cracker catalyst is a fine powder (looks like baby powder) that behaves like a fluid when agitated - hence 'fluid cat cracking' (FCC). Under a microscope, each particle has enormous surface area from pores, maximizing contact with the oil feed.",
x:"The catalyst's surface area is critical because cracking efficiency depends on contact between the catalyst and the feed. Older catalyst forms (beads, 1/8 to 1/4 inch diameter) are mostly out of vogue. Modern catalyst particles are so fine they behave as a fluid - they can be pumped through pipes and circulated continuously."},
{t:"The Three-Part System: Reactor, Regenerator, Fractionator",h:"Crack, clean, separate - two circular flows running simultaneously",
b:"The cat cracker has three sections: (1) The Reaction Chamber/Riser - feed meets hot catalyst, cracking happens in seconds. In modern crackers, all cracking occurs in the riser pipe before even reaching the reactor vessel, which is just a catalyst separator. (2) The Regenerator - spent catalyst (coated in coke) is mixed with 1,100°F heated air. The coke burns off (C + O2 → CO2), generating enormous heat and cleaning the catalyst. (3) The Fractionator - cracked products are separated into gas, gasoline, light gas oil, heavy gas oil, and cycle oil.",
x:"Two circular flows happen simultaneously: catalyst loops between reactor and regenerator continuously, while hydrocarbon enters the fractionator and some cycle oil recirculates back to the reactor feed. Cycle oil can be 'recycled to extinction' - run through repeatedly until it all cracks."},
{t:"Cat Cracker Yields and the Magic of 'Gain'",h:"100% goes in, 118% comes out. It's physics, not magic.",
b:"Typical cat cracker yields from 100% feed: 55% cat cracked gasoline, 35% C4 and lighter gases (including valuable olefins), 12% light gas oil, 8% heavy gas oil, and 8% coke burned off the catalyst. Total product volume: 118%. This 'gain' happens because cracking converts dense heavy molecules into lighter, less dense molecules. By weight, input equals output. By volume, output exceeds input since products are sold by volume, refiners love this.",
x:"The C4 and lighter stream from the cat cracker contains olefins (propylene, butylenes) that aren't present in straight-run gases. These go to the cracked gas plant, not the sats gas plant. The isobutane, propylene, and butylenes are particularly valuable as alkylation feed."},
{t:"Process Variables and the Time-of-Day Effect",h:"Cat cracker yields actually change between day and night because of air temperature",
b:"Cat cracker yields are affected by feed quality (gravity, PONA content), reactor temperature (higher = more cracking but more gas at the expense of gasoline), feed rate, and recycle rate. But the most surprising variable is outdoor air temperature. The regenerator blowers run at fixed speed. Cold night air is denser, delivering more oxygen. More oxygen burns more coke off the catalyst. Cleaner catalyst cracks better, making more gasoline.",
x:"You can actually see this in operator logs: yields improve as night falls and temperature drops, then decline during hot afternoons. Summer vs. winter has the same pattern - unfortunately, gasoline demand peaks in summer when cat cracker yields are at their worst due to hot air."},
{t:"Refinery Flow So Far",h:"Distilling → Flashing → Cat Cracking - how the pieces connect",
b:"At this point, the refinery flow diagram shows crude entering the distilling column, producing multiple cuts. The heavy gas oil and flasher tops flow to the cat cracker. Cat cracker products include: gases (to gas plant), cat gasoline (to blending), cat light gas oil (to distillate fuel), and cat heavy gas oil (to fuel oil blending or further processing). The light gas oil cut point can be adjusted seasonally - wider for winter heating oil demand, narrower for summer gasoline.",
x:"The cat cracked gasoline is a good motor gasoline blending component. The cracked light gas oil is a decent distillate fuel blendstock. The gases contain olefins that will feed the alkylation unit - our next conversion process."}
],
quiz:[
{q:"Leffler compares catalysts to:",o:["Hardworking adults","Troublesome ten-year-olds who never get in trouble but wherever they go, trouble happens","Gentle teachers","Slow-moving turtles"],c:1,e:"Leffler's memorable analogy: catalysts cause reactions without being changed themselves. They don't get into trouble, but wherever they go, trouble (reactions) happen."},
{q:"In modern FCC units, where does most of the cracking actually take place?",o:["In the reactor vessel over several minutes","In the riser pipe in just seconds","In the regenerator","In the fractionator"],c:1,e:"In modern cat crackers, virtually all cracking occurs in the riser pipe as feed and hot catalyst rush upward. The reactor vessel is mainly used as a catalyst/hydrocarbon separator."},
{q:"Cat cracker products total 118% by volume of the feed. How is this possible?",o:["Extra molecules come from the catalyst","Cracked molecules are less dense, so they take up more volume per pound","Moisture is added during cracking","The fractionator adds volume"],c:1,e:"Cracking converts dense heavy molecules into lighter, less dense ones. By weight, 100% in = 100% out. But by volume, output exceeds input because lighter molecules take up more space. This is 'volume gain.'"},
{q:"Why do cat cracker yields improve at night?",o:["Operators work harder at night","Cold night air is denser, delivering more oxygen to the regenerator, burning more coke off catalyst","Less crude is processed at night","The catalyst works better in the dark"],c:1,e:"The air blowers run at fixed speed. Colder night air is denser = more oxygen molecules per cubic foot = more coke burned off = cleaner catalyst = better cracking yields. It's pure physics."},
{q:"The C4 and lighter gases from the cat cracker differ from distilling unit gases because they contain:",o:["More methane","Olefins (propylene, butylenes) that aren't in straight-run gas","Less ethane","Hydrogen sulfide"],c:1,e:"Cracking creates olefins (propylene, butylenes) that aren't present in straight-run (uncracked) gas streams. These go to the cracked gas plant, not the sats gas plant."},
{q:"Approximately what percentage of cat cracker output is gasoline?",o:["20%","35%","55%","80%"],c:2,e:"Typical cat cracker gasoline yield is about 55% by volume of the feed - making it the primary gasoline-producing conversion unit in most refineries."}
]},

// Chapters VII-XXI continue with similar depth...
// For space, I'll include the remaining chapters with enriched content

// ===================== CHAPTER VII =====================
{id:7,n:"VII",t:"Refinery Gas Plants",d:"Separating the light gases - methane, ethane, propane, butanes - each to its highest-value use",
concepts:[
{t:"Sats Gas Plant vs. Cracked Gas Plant",h:"Stable saturates vs. reactive olefins - they go to different plants",
b:"Gas streams from most refinery units contain only saturated hydrocarbons: methane, ethane, propane, butanes, and maybe hydrogen. These go to the sats gas plant. But streams from the cat cracker and other crackers also contain olefins (ethylene, propylene, butylenes). These go to the cracked gas plant because the olefins have different destinations (mainly alkylation).",
x:"The word 'saturates' means all carbon atoms are fully saturated with hydrogen - no double bonds. Separating these gases is much harder than crude distilling because each gas is a pure chemical with a single boiling point - there's zero tolerance for sloppy separation. Many trays, lots of reflux and reboil."},
{t:"The Seven Steps of Gas Separation",h:"Compress → phase separate → absorb → debutanize → depropanize → deisobutanize → sponge absorb",
b:"Step 1: Compress gases to ~200 psi. Step 2: Phase separation (high pressure liquefies some gas). Step 3: Remaining gas enters the 'rectified absorber' where lean oil (naphtha) trickles down absorbing propane and butane, becoming 'fat oil.' Step 4: Debutanizer separates C3/C4 from naphtha (easy - naphtha boils at 180°F, butane at 32°F). Step 5: Depropanizer splits propane from butanes. Step 6: Deisobutanizer splits normal butane from isobutane (hardest split - they boil only 20°F apart). Step 7: Sponge absorber recovers lean oil that vaporized during absorption.",
x:"The deisobutanizer is usually the tallest column in the gas plant because isobutane (11°F) and normal butane (31°F) boil so close together. Many trays are needed. In contrast, the naphtha/butane split is easy because their boiling points are nearly 150°F apart."},
{t:"Where Each Gas Goes",h:"Every molecule has a unique highest-value destination",
b:"Isobutane → almost entirely to alkylation feed. Normal butane → motor gasoline blending (cheap, volatile, good for cold starts). Propane → LPG sales (easily liquefied at reasonable pressure for truck transport, readily vaporizes at ambient temps for stoves and furnaces). Ethane → chemical feedstock (ethylene plants) or left with methane as fuel. Methane → refinery fuel for furnaces and boilers (never stored, sent directly to fuel system).",
x:"LPG storage is distinctive: spherical tanks or 'bullets' (cylinders) for above-ground, or salt dome caverns underground. The round shapes optimize structural strength vs. cost for high-pressure storage. Salt dome caverns are created by dissolving salt with water - expandable by using fresh water to dissolve more salt from the walls."},
{t:"Cracked Gas Plant and Hydrogen",h:"Olefins go to alkylation; hydrogen goes to hydrotreaters",
b:"The cracked gas plant handles streams containing olefins (propylene, butylenes) from the cat cracker. Usually propylene and butylenes are sent to alkylation together with isobutane. The reformer gas stream is often kept separate because it's rich in hydrogen. After compression, the hydrogen can be separated as an H2/methane concentrate for use in hydrotreating and hydrocracking units.",
x:"Some processes in the refinery produce hydrogen (reforming), while others consume it (hydrotreating, hydrocracking). Balancing this hydrogen supply and demand is one of the most critical logistical challenges in refinery operations."}
],
quiz:[
{q:"Why is gas separation harder than crude distillation?",o:["Gases are invisible","Each gas is a pure chemical boiling at a single temperature - no tolerance for sloppy separation","Gas plants are smaller","Gases are more flammable"],c:1,e:"In crude distilling, fractions are ranges of compounds that blend together tolerantly. Each gas is a single compound with a precise boiling point - separation must be extremely clean."},
{q:"'Fat oil' in the gas plant is:",o:["Crude oil with too much residue","Lean oil (naphtha) that has absorbed propane and butane from the gas","Oil that has too high a viscosity","A waste product"],c:1,e:"Clean naphtha (lean oil) is pumped into the top of the absorber. As it trickles down, it absorbs propane and butane from the rising gas, becoming 'fat oil.' Clever naming from the engineers."},
{q:"Isobutane from the gas plant is primarily sent to:",o:["Direct sale as LPG","Gasoline blending","The alkylation unit as feed","The reformer"],c:2,e:"Isobutane is the key feedstock for alkylation, where it combines with olefins (propylene, butylenes) to make high-octane alkylate gasoline."},
{q:"Normal butane is mainly used for:",o:["Alkylation feed","Motor gasoline blending (adjusts vapor pressure)","Chemical feedstock","Jet fuel blending"],c:1,e:"Normal butane is blended into gasoline. Its high volatility helps with cold engine starts, and it's cheap. More butane is blended in winter (higher RVP spec) than summer."},
{q:"Why are LPG tanks spherical?",o:["Spheres look nice","Spheres optimize structural strength vs. steel cost for high-pressure storage","Spheres roll for easy transport","Regulations require spherical shape"],c:1,e:"Propane and butane are stored under pressure. Spherical geometry provides the best ratio of structural strength to material cost for containing pressurized liquids."}
]},

// ===================== CHAPTER VIII =====================
{id:8,n:"VIII",t:"Alkylation",d:"Combining small molecules into premium gasoline - the reverse of cracking",
concepts:[
{t:"The Inverse of Cracking",h:"Cracking breaks apart. Alkylation builds up. Volume SHRINKS instead of expanding.",
b:"Alkylation reacts propylene or butylene (olefins from the cat cracker) with isobutane (from the gas plant) to form large, branched iso-paraffins called 'alkylate.' The volume effect is opposite to cracking: 1 bbl butylene + 1.2 bbl isobutane = only 1.8 bbl product (shrinkage). With propylene: 1 bbl + 1.6 bbl isobutane = 2.1 bbl product. Weight in = weight out, but the larger molecules are denser.",
x:"This is the mirror image of cat cracking's volume 'gain.' In cracking, dense molecules break into less dense pieces (volume expands). In alkylation, light molecules combine into denser ones (volume shrinks). Refiners dislike shrinkage but love the product quality."},
{t:"The Catalysts: HF vs. H2SO4",h:"Two dangerous acids, two different trade-offs, one big refinery design decision",
b:"Alkylation uses one of two acid catalysts: Hydrofluoric acid (HF) operates at moderate temperature and pressure, needs less acid, but if leaked forms a deadly airborne toxic cloud. Sulfuric acid (H2SO4) requires refrigeration (40-50°F), consumes much more acid, but if leaked pools on the ground rather than forming a cloud. The choice is one of the biggest design decisions in refinery planning.",
x:"Urban refineries generally prefer H2SO4 because of the airborne release risk of HF. But H2SO4 units have higher operating costs due to refrigeration and acid consumption. Some refineries have converted from HF to H2SO4 due to community pressure, despite the cost increase."},
{t:"Alkylate: The Perfect Gasoline Component",h:"95-97 RON, clean burning, zero sulfur, zero olefins, zero aromatics",
b:"Alkylate is a refiner's dream blendstock: 95-97 Research Octane Number, low Reid Vapor Pressure, no sulfur, no aromatics, no olefins, clean burning. Aviation gasoline (avgas) is almost entirely alkylate. It's so good that the limiting factor is always supply of isobutane and olefins, never demand for alkylate.",
x:"Alkylate's quality comes from its molecular structure: large, highly branched iso-paraffins. Branching provides high octane (resists knocking). The saturated bonds provide stability (no olefins to cause gum formation). No aromatic rings means clean burning with less particulate emissions."}
],
quiz:[
{q:"In alkylation, 1 bbl butylene + 1.2 bbl isobutane produces:",o:["2.2 bbl of product (no change)","2.5 bbl of product (volume gain)","1.8 bbl of product (volume shrinkage)","1.0 bbl of product (half is lost)"],c:2,e:"Alkylation causes volume shrinkage (opposite of cracking). Small, less dense molecules combine into larger, denser ones. Same weight in and out, but less volume out."},
{q:"Why might an urban refinery prefer sulfuric acid over HF for alkylation?",o:["H2SO4 is cheaper","H2SO4 makes better alkylate","If H2SO4 leaks, it pools on the ground rather than forming an airborne toxic cloud like HF","H2SO4 doesn't need any special equipment"],c:2,e:"HF releases form deadly airborne toxic clouds. H2SO4 is heavier than air and pools on the ground. For refineries near residential areas, H2SO4 is safer despite higher operating costs."},
{q:"Alkylate has a RON of approximately:",o:["70-75","80-85","88-91","95-97"],c:3,e:"Alkylate has an excellent 95-97 RON, making it one of the highest-octane gasoline blending components. It's also clean-burning with no sulfur, olefins, or aromatics."},
{q:"Aviation gasoline (avgas) is primarily made of:",o:["Cat cracked gasoline","Straight-run naphtha","Alkylate","Reformate"],c:2,e:"Aviation gasoline is almost entirely alkylate because its high octane, clean-burning properties, and stability are ideal for aircraft engines where reliability is critical."},
{q:"The two feedstocks for alkylation are:",o:["Crude oil and natural gas","Olefins (propylene/butylene) and isobutane","Gasoline and diesel","Naphtha and kerosene"],c:1,e:"Alkylation combines olefins (from the cat cracker) with isobutane (from the gas plant) to make large, branched alkylate molecules."}
]},

// ===================== CHAPTER IX =====================
{id:9,n:"IX",t:"Catalytic Reforming",d:"Reshaping naphtha molecules to boost octane and produce hydrogen",
concepts:[
{t:"What Reforming Actually Does to Molecules",h:"Same number of carbons, completely different shape - and a dramatic octane boost",
b:"Catalytic reforming rearranges the molecular structure of straight-run naphtha (low octane, ~40-60 RON) into reformate (high octane, 90-100+ RON). Three main reactions: (1) Naphthenes → aromatics (huge octane gain, releases hydrogen), (2) Paraffins → isoparaffins (moderate octane gain via branching), (3) Paraffins → aromatics (major restructuring, releases lots of hydrogen). The molecule sizes don't change much - it's the shape that transforms.",
x:"The naphthene-to-aromatic reaction is the most important. A six-carbon naphthene ring loses 3 hydrogen molecules and becomes a benzene ring. The octane jumps dramatically. This is why feed with high naphthene content gives the best reforming results."},
{t:"The Platinum Catalyst",h:"Yes, the same precious metal as in jewelry - used at 0.3-0.6% concentration",
b:"Reforming uses a platinum-based catalyst on an alumina support, operating at 900-980°F and moderate pressures. Platinum is so effective it works at very low concentrations (0.3-0.6% by weight). Sometimes rhenium or tin is added as a second metal. The catalyst gradually deactivates as coke deposits on it. Semi-regenerative units shut down periodically to burn off coke; continuous units circulate catalyst through a regenerator while running.",
x:"Platinum's effectiveness at such low concentrations makes the economics work despite its precious metal cost. The catalyst is carefully managed and eventually sent back to the supplier for precious metal recovery - every gram of platinum is tracked."},
{t:"Hydrogen: The Reformer's Gift to the Refinery",h:"One of the ONLY processes that produces hydrogen instead of consuming it",
b:"Reforming is one of the few refinery processes that produces hydrogen rather than consuming it. As naphthenes lose hydrogen atoms to become aromatics, free H2 gas is released - typically 1,000-2,000 standard cubic feet per barrel of feed. This hydrogen is critical because it feeds the refinery's hydrotreaters and hydrocrackers, which consume large quantities of H2.",
x:"The hydrogen balance is one of the most important constraints in refinery planning. The reformer is the primary H2 source. If hydrogen demand exceeds reformer supply, a dedicated steam methane reformer (SMR) must make up the difference at significant cost. This makes the reformer a strategically vital unit."},
{t:"Reforming Severity and Octane",h:"Push harder for higher octane, but you lose more volume",
b:"Reforming severity can be adjusted by changing temperature and space velocity (how long feed stays on the catalyst). Higher severity = higher octane reformate, but also more volume loss (more molecules crack into gases) and faster catalyst deactivation. Typical trade-off: 94 RON reformate at moderate severity vs. 100+ RON at high severity but with significantly lower liquid yield.",
x:"Refiners optimize severity based on the octane requirements of their gasoline pool and the value of additional octane vs. the cost of losing liquid volume. During high-octane demand periods (like summer driving season), severity may be increased."}
],
quiz:[
{q:"The PRIMARY molecular transformation in reforming is:",o:["Breaking large molecules into small ones","Converting naphthenes to aromatics (releasing hydrogen)","Combining small molecules into large ones","Removing sulfur from hydrocarbons"],c:1,e:"The most important reforming reaction converts naphthenes (saturated rings) to aromatics (benzene rings), releasing hydrogen and dramatically increasing octane number."},
{q:"Why is the reformer called 'the refinery's hydrogen factory'?",o:["It buys hydrogen from outside suppliers","It's one of the few processes that PRODUCES hydrogen rather than consuming it","It stores hydrogen for other units","It converts water to hydrogen"],c:1,e:"As naphthenes lose hydrogen atoms to become aromatics, free H2 is released - 1,000-2,000 scf per barrel. Most other processes (hydrotreating, hydrocracking) consume hydrogen."},
{q:"The reformer catalyst contains platinum at what concentration?",o:["50% by weight","10-20% by weight","0.3-0.6% by weight","Trace amounts too small to measure"],c:2,e:"Platinum is so effective that it works at just 0.3-0.6% by weight on an alumina support. Despite the precious metal cost, the economics work because so little is needed."},
{q:"Higher reforming severity means:",o:["Lower octane but more liquid yield","Higher octane but less liquid yield and faster catalyst aging","No change in either octane or yield","Higher volume gain like cat cracking"],c:1,e:"Pushing reforming severity higher produces higher-octane reformate, but more feed molecules crack into gases (reducing liquid yield) and the catalyst deactivates faster."},
{q:"Reforming feed is typically:",o:["Heavy gas oil from the distilling column","Straight-run naphtha (low octane, 40-60 RON)","Flasher bottoms","Cat cracked gasoline"],c:1,e:"Straight-run naphtha from the crude distilling unit has low octane (40-60 RON) and needs reforming to boost it to 90-100+ RON before it's useful as gasoline."}
]},

// ===================== CHAPTER X =====================
{id:10,n:"X",t:"Residue Reduction",d:"Thermal cracking, visbreaking, and delayed coking - squeezing value from the bottom of the barrel",
concepts:[
{t:"Visbreaking: Gentle Cracking to Reduce Viscosity",h:"Just enough cracking to make heavy residue flow - the name says it all",
b:"Visbreaking ('viscosity breaking') applies mild thermal cracking at 850-900°F to heavy residue. The goal isn't to maximize conversion - it's just to reduce the viscosity enough that the residue can be pumped, transported, and burned. Only about 10-15% of the feed converts to lighter products. The rest remains as lower-viscosity residual fuel.",
x:"Visbreaking reduces the amount of expensive 'cutter stock' (light cycle oil) needed to thin residual fuel to spec. Even a small viscosity reduction saves money because less valuable light product needs to be sacrificed as a diluent."},
{t:"Delayed Coking: Maximum Conversion from the Bottom",h:"Cook the residue until it turns into solid carbon - then blast it out with water jets",
b:"Delayed coking is the most severe form of thermal cracking. Residue is heated to very high temperatures in a furnace, then sent to a large drum (the 'coke drum'). Light products vaporize off the top and go to a fractionator. The remaining carbon solidifies into petroleum coke - a solid mass that fills the drum. Two drums alternate: one fills while the other is being 'de-coked' by cutting the solid coke out with high-pressure water jets (3,000+ psi).",
x:"Products from the coker: gases, coker naphtha, coker gas oil (sent to the cat cracker or hydrocracker for upgrading), and solid petroleum coke. The coke can be fuel-grade (burned in cement kilns or power plants), anode-grade (used in aluminum smelting), or needle coke (premium product for graphite electrodes in steel electric arc furnaces)."},
{t:"Flexicoking and Fluid Coking",h:"Variations that gasify or fluidize the coke for different economics",
b:"Fluid coking uses a fluidized bed of hot coke particles as the heat source instead of a furnace. Residue is sprayed onto the hot coke particles, cracking occurs instantly, and vapors are recovered. Flexicoking takes it further by gasifying the coke into a low-BTU fuel gas, leaving almost no solid coke waste. Both are alternatives to delayed coking with different capital and operating cost trade-offs.",
x:"The choice between visbreaking, delayed coking, and fluid coking depends on crude slate, product demand, and capital availability. Visbreaking is cheap to build but doesn't convert much. Delayed coking is expensive but converts almost everything to lighter products plus solid coke."}
],
quiz:[
{q:"Visbreaking's primary goal is:",o:["Maximize gasoline production","Reduce viscosity of heavy residue so it can be pumped and burned","Produce solid coke for sale","Remove sulfur from residue"],c:1,e:"Visbreaking = viscosity breaking. It mildly cracks residue just enough to make it flow more easily, reducing the need for expensive cutter stock."},
{q:"In delayed coking, how is the solid petroleum coke removed from the drums?",o:["It melts and pours out","It's dissolved in chemicals","High-pressure water jets (3,000+ psi) cut it out","It's vacuumed out"],c:2,e:"After a coke drum is full, operators switch to the spare drum and use high-pressure water jets at 3,000+ psi to cut the solid coke mass out of the full drum. It's a dramatic operation."},
{q:"Coker gas oil is typically sent to:",o:["Gasoline blending directly","The cat cracker or hydrocracker for further upgrading","LPG storage","Asphalt production"],c:1,e:"Coker gas oil still needs conversion - it goes to the cat cracker or hydrocracker where it's broken down into finished gasoline and diesel components."},
{q:"Which is the MOST severe form of residue processing?",o:["Visbreaking","Vacuum flashing","Delayed coking","Hydrotreating"],c:2,e:"Delayed coking is the most severe thermal process - it converts residue all the way to light products plus solid carbon (coke). Visbreaking is mild; vacuum flashing is just separation, not cracking."},
{q:"Delayed cokers use TWO drums because:",o:["One drum isn't big enough","One fills with coke while the other is being de-coked - they alternate","Regulations require redundancy","Two drums produce better quality coke"],c:1,e:"The operation is continuous - while one drum fills with coke over 12-24 hours, the other is being cooled, de-coked (water jets), and prepared for the next fill cycle."}
]},

// ===================== CHAPTER XI =====================
{id:11,n:"XI",t:"Hydrocracking",d:"Cracking with hydrogen - the most flexible and cleanest conversion process",
concepts:[
{t:"Cat Cracking + Hydrogen = Superior Products",h:"Same idea as cat cracking, but hydrogen fills the broken bonds for cleaner results",
b:"Hydrocracking combines catalytic cracking with large volumes of high-pressure hydrogen (1,500-2,500 psi, 650-800°F). When molecules crack, the hydrogen immediately saturates the broken bonds. This produces much cleaner products than cat cracking: very low sulfur, very low aromatics, excellent stability. The trade-off: much more expensive equipment due to extreme pressures.",
x:"In cat cracking, the lack of hydrogen during cracking causes olefins, aromatics, and coke to form. In hydrocracking, abundant hydrogen prevents these byproducts - the products are almost entirely saturated (paraffins and naphthenes), with near-zero sulfur."},
{t:"The Ultimate Product Flexibility",h:"Adjust the dial: more gasoline today, more diesel tomorrow",
b:"By changing severity (temperature, catalyst type, space velocity), a hydrocracker can swing its product slate from predominantly gasoline to predominantly middle distillates (jet fuel, diesel). No other conversion unit offers this degree of product flexibility. Feed flexibility is also excellent - it can process gas oil, coker gas oil, deasphalted oil, and other feeds.",
x:"This flexibility is strategically valuable. When diesel and jet fuel margins are high (winter heating season, strong airline demand), the hydrocracker swings to maximize distillate. When gasoline margins spike (summer driving season), it can shift the other way. This ability to respond to market signals is worth the high capital cost."},
{t:"Hydrocracked Product Quality",h:"So clean you could almost drink it (don't though)",
b:"Hydrocracked products are among the cleanest in the refinery. Hydrocracked naphtha has good octane and very low sulfur. Hydrocracked diesel and jet fuel have very low sulfur, very low aromatics, excellent cold-flow properties, and high cetane numbers. The products often exceed finished specifications with minimal additional treatment.",
x:"Hydrocracked jet fuel is particularly prized for its low freeze point and high thermal stability. Hydrocracked diesel has high cetane numbers because the saturated, paraffinic molecules ignite easily under compression. These premium qualities justify the hydrocracker's high operating cost."}
],
quiz:[
{q:"Hydrocracking differs from cat cracking primarily because:",o:["It uses lower temperatures","High-pressure hydrogen fills broken bonds during cracking, producing cleaner products","It only processes light feeds","It doesn't use a catalyst"],c:1,e:"The key difference is hydrogen. In hydrocracking, abundant H2 at high pressure saturates broken bonds, preventing olefins, aromatics, and coke formation. Products are much cleaner."},
{q:"Hydrocrackers typically operate at pressures of:",o:["50-100 psi","200-400 psi","1,500-2,500 psi","10,000-15,000 psi"],c:2,e:"Hydrocrackers require very high pressures of 1,500-2,500 psi to maintain hydrogen in intimate contact with the feed during cracking. This drives the high equipment cost."},
{q:"The hydrocracker's key strategic advantage over the cat cracker is:",o:["Lower capital cost","Ability to swing product slate between gasoline and diesel/jet based on market demand","Higher volume gain","Simpler operation"],c:1,e:"No other conversion unit offers the hydrocracker's flexibility to shift output from mostly gasoline to mostly diesel/jet fuel (or vice versa) as market prices change."},
{q:"Why are hydrocracked diesel and jet fuel considered 'premium' quality?",o:["They have a nicer color","Very low sulfur, low aromatics, high cetane, excellent cold-flow properties","They come from more expensive crude","They contain special additives"],c:1,e:"Hydrogen saturation produces clean, paraffinic products with near-zero sulfur, few aromatics, high cetane numbers, and excellent cold-flow and stability properties."}
]},

// ===================== CHAPTER XII =====================
{id:12,n:"XII",t:"Gasoline Blending",d:"The art of mixing components to meet octane, vapor pressure, and all other specs simultaneously",
concepts:[
{t:"The Four-Stroke Engine Cycle",h:"Intake → compress → power → exhaust. Gasoline specs exist because of how engines work.",
b:"Understanding gasoline specs requires understanding engines. The four-stroke cycle: (1) Intake - piston goes down, inlet valve opens, gasoline/air mixture enters the cylinder. (2) Compression - piston goes up, compressing the vapor. (3) Power - spark plug fires, gasoline burns explosively, pushing the piston down. (4) Exhaust - exhaust valve opens, burnt fuel is pushed out. Each cycle = two trips up and down the cylinder.",
x:"Every gasoline specification traces back to engine performance. Vapor pressure determines whether gasoline will vaporize properly for starting and running. Octane number determines whether it will burn smoothly or knock. Understanding the engine makes the specs intuitive."},
{t:"Reid Vapor Pressure (RVP)",h:"Too much = vapor lock in summer. Too little = won't start in winter. Butane is the dial.",
b:"RVP measures the surface pressure needed to keep gasoline liquid. High RVP = very volatile. Winter gasoline needs high RVP (~13 psi in Bemidji, Minnesota) for cold starts. Summer gasoline needs low RVP (~8.5 psi in Presidio, Texas) to prevent vapor lock. Normal butane (RVP = 52 psi) is the primary tool - add more for winter, less for summer.",
x:"Vapor lock occurs at high altitude + high temperature: the fuel pump tries to pump a mix of vapor and liquid (designed for liquid only), starving the carburetor. The car quits and won't restart until the gasoline cools down - could take hours. RVP specs are localized to each region's altitude and seasonal temperatures."},
{t:"Octane Numbers: RON, MON, and the Pump Posting",h:"The measure of whether your gasoline will knock",
b:"Octane number measures resistance to knocking (self-ignition under compression). Iso-octane (C8H18, branched) was defined as 100 octane. Normal heptane (C7H16, straight chain) was defined as 0 octane. RON (Research Octane Number) tests simulate mild driving. MON (Motor Octane Number) tests simulate severe conditions. The FTC mandated gas pumps post (RON+MON)/2 as a compromise after a controversy between the FTC and refiners.",
x:"Higher compression ratio = more powerful engine but requires higher octane fuel. If gasoline self-ignites before the spark plug fires, the premature combustion pushes back against the rising piston, causing the 'knocking' sound and potential engine damage. Octane number guarantees the gasoline won't do this."},
{t:"Blending Components and Calculation",h:"Reformate, alkylate, cat gasoline, straight-run naphtha, butane - mixing for specs",
b:"Key blending components with typical octane numbers: straight-run gasoline (61 MON / 66 RON), reformate 94 RON (~75 MON), reformate 100 RON (~85 MON), alkylate (96 MON / 97 RON), cat cracked gasoline (78 MON / 93 RON), normal butane (92 MON / 93 RON), light hydrocrackate (85 MON / 84 RON). The blender calculates weighted averages and solves for how much of each component to use.",
x:"A sample RVP calculation: if you have 19,000 bbl of gasoline components averaging 3.2 psi RVP and need 10 psi RVP total, you'd add about 3,081 bbl of normal butane (52 psi RVP). More butane in winter = more total gasoline volume = higher production capacity in winter than summer."},
{t:"Seasonal Gasoline Economics",h:"Winter = more gasoline (more butane). Summer = less gasoline (less butane). Counterintuitive!",
b:"Since winter RVP specs are higher, more butane is blended in. Butane is cheap and adds volume. So gasoline production capacity is actually HIGHER in winter than summer. In summer, less butane means less total gasoline. Meanwhile, gasoline demand peaks in summer. This supply-demand mismatch creates seasonal price patterns - prices tend to rise in spring as refineries switch from winter to summer specs.",
x:"There's also a battle for isobutane between gasoline blending (as normal butane) and alkylation (as isobutane feed). Sometimes normal butane must be isomerized to isobutane to satisfy alkylation demand. The interplay between these uses makes butane one of the most strategically important molecules in the refinery."}
],
quiz:[
{q:"The number posted on gas pumps - (RON+MON)/2 - exists because:",o:["It's a technically meaningful measure","The FTC mandated it as a compromise after refiners objected to posting RON alone","Refiners chose it as their preferred metric","It's required by engine manufacturers"],c:1,e:"The FTC wanted RON posted. Refiners said RON didn't tell the whole story. RON+MON was 'too confusing.' The compromise: (RON+MON)/2, which doesn't have particular technical meaning but ended the controversy."},
{q:"Why is gasoline production capacity HIGHER in winter?",o:["Refineries run harder in cold weather","More cheap butane is blended in to meet higher RVP spec, adding volume","Winter crude is lighter","Taxes are lower in winter"],c:1,e:"Higher winter RVP spec = more butane blended in. Butane is cheap and adds volume. So winter gasoline has more barrels than summer gasoline, even though demand is lower."},
{q:"Vapor lock is caused by:",o:["Too little gasoline","Gasoline vaporizing in the fuel system at high altitude/temperature, starving the engine","Water contamination","A clogged fuel filter"],c:1,e:"High altitude (low pressure) + high temperature causes high-RVP gasoline to vaporize in the fuel lines. The pump can't handle vapor, so the carburetor starves and the engine quits."},
{q:"What is 'knocking' in an engine?",o:["A broken piston","Self-ignition of the gasoline/air mixture BEFORE the spark plug fires","Too much exhaust buildup","Fuel injector noise"],c:1,e:"Knocking happens when compressed gasoline-air mixture gets hot enough to self-ignite before the spark plug fires. This premature combustion pushes against the rising piston, causing the knock sound."},
{q:"Cat cracked gasoline has a Research Octane Number of about:",o:["60","78","93","100"],c:2,e:"Cat cracked gasoline has about 93 RON (78 MON). The olefins and aromatics created during cracking give it good octane. It's the largest single component of the gasoline pool."},
{q:"How much normal butane (52 psi RVP) would you add to 19,000 bbl averaging 3.2 psi RVP to reach 10 psi total?",o:["About 1,000 bbl","About 3,000 bbl","About 8,000 bbl","About 15,000 bbl"],c:1,e:"The calculation (weighted average): 10×(19000+x) = 19000×3.2 + 52x, solving gives x ≈ 3,081 bbl. About 3,000 barrels of butane to pressure up the blend."}
]},

// Chapters XIII-XXI with enriched content (keeping reasonable size)
{id:13,n:"XIII",t:"Distillate Fuels",d:"Diesel, jet fuel, heating oil - the middle distillates that power transport and heat homes",
concepts:[
{t:"Diesel Fuel and the Cetane Number",h:"The ANTI-octane: diesel engines NEED fuel to self-ignite. Gasoline engines need fuel to NOT self-ignite.",
b:"Diesel engines have no spark plugs. Air is compressed until it's so hot that fuel self-ignites when injected. Cetane number measures this ignition quality (higher = better, easier ignition). Cetane (C16H34, a straight-chain paraffin) was defined as 100. Here's the irony: straight-chain paraffins have HIGH cetane (great diesel) but LOW octane (terrible gasoline). Aromatics have HIGH octane (great gasoline) but LOW cetane (terrible diesel).",
x:"This molecular tension drives much of refinery planning. The same molecules that make great gasoline are terrible for diesel, and vice versa. Refiners must allocate each molecular type to its best use."},
{t:"Jet Fuel: Kerosene That Can't Freeze at 35,000 Feet",h:"At -60°F outside temperature, wax crystals could kill the engines",
b:"Jet fuel (Jet-A) is essentially kerosene from the 315-450°F boiling range, with critical specs on freezing point (must stay liquid at -40°F), thermal stability, and cleanliness. At 35,000 feet, outside temperatures reach -60°F. If wax crystals form in the fuel, they can block fuel filters and starve the engines. The freeze point spec is one of the most critical constraints in jet fuel production.",
x:"Heating oil and diesel are chemically very similar - the main differences are specifications and taxation. Home heating oil can tolerate higher sulfur and wider spec ranges than highway diesel. In many markets, diesel and heating oil are essentially the same product with different taxes."}
],
quiz:[
{q:"Normal (straight-chain) paraffins are GOOD for diesel but BAD for gasoline because:",o:["They cost more","High cetane (easy ignition for diesel) but low octane (knocks in gasoline engines)","They have too much sulfur","They evaporate too easily"],c:1,e:"Straight-chain paraffins ignite easily under compression (high cetane = good diesel) but also self-ignite prematurely in gasoline engines (low octane = knocking). Structure determines destination."},
{q:"The most critical spec for jet fuel at high altitude is:",o:["Octane number","Color","Freeze point (must stay liquid at -40°F to prevent wax crystal blockage)","Viscosity"],c:2,e:"At 35,000 feet with outside temps of -60°F, wax crystals forming in jet fuel could block fuel filters and starve the engines. The freeze point spec prevents this catastrophe."},
{q:"Diesel and home heating oil are:",o:["Completely different products","Chemically very similar - differ mainly in specs and taxation","Made from different parts of the barrel","Never made at the same refinery"],c:1,e:"Diesel and heating oil come from the same boiling range and are chemically similar. The main differences are specification tightness (diesel specs are stricter) and taxation."}
]},

{id:14,n:"XIV",t:"Asphalt & Residual Fuel",d:"The heaviest products from the bottom of the barrel",
concepts:[
{t:"Residual Fuel Oil: Viscosity Is Everything",h:"So thick it must be heated just to pump it. 'Cutter stock' thins it out.",
b:"Residual fuel oil is blended from the heaviest refinery streams for use in ships, power plants, and industrial furnaces. The key specification is viscosity - the fuel must be thin enough to spray through burner nozzles and atomize properly for combustion. Lighter 'cutter stock' (typically cat cracked light cycle oil) is blended in to reduce viscosity to acceptable levels.",
x:"Using light cycle oil as cutter stock means sacrificing a product that could be sold as diesel blendstock. This economic penalty is one reason refiners invest in conversion units (cat crackers, cokers) to upgrade heavy residue into lighter, more valuable products instead."},
{t:"Asphalt: Not All Crudes Can Make It",h:"Only heavy, naphthenic 'asphalt-base' crudes produce good road-paving material",
b:"Asphalt comes from vacuum flasher bottoms, but not all crudes make good asphalt. Only heavy, naphthenic (asphalt-base) crudes produce the right consistency. Paraffinic crudes produce waxy residues that don't work for paving. Asphalt is graded by penetration - how far a standard needle sinks into it under specified conditions. The refiner controls hardness by adjusting the flasher cut point.",
x:"More light material left in the flasher bottoms = softer asphalt. Deeper cutting (taking more light material overhead) = harder asphalt. Different applications (highways vs. parking lots vs. roofing) need different grades."}
],
quiz:[
{q:"'Cutter stock' is blended into residual fuel to:",o:["Add sulfur","Reduce viscosity so it can be pumped and sprayed through burner nozzles","Increase its energy content","Improve its color"],c:1,e:"Heavy residual fuel is too viscous to pump or atomize in burners. Lighter cutter stock (usually cat cracked light cycle oil) is blended in to reduce viscosity to a workable level."},
{q:"Why can't paraffinic crudes make good asphalt?",o:["They're too expensive","They produce waxy residues that don't have the right paving properties","They're too light","They contain too much sulfur"],c:1,e:"Paraffinic crudes produce waxy, crystalline residues that don't bind and flex properly for road paving. Only heavy naphthenic crudes produce the amorphous, adhesive material needed for good asphalt."}
]},

{id:15,n:"XV",t:"Hydrogen, Hydrotreating & Sulfur",d:"Cleaning up products with hydrogen and turning waste H2S into sellable sulfur",
concepts:[
{t:"Hydrotreating: The Refinery's Environmental Workhorse",h:"Pass any stream over a catalyst with hydrogen: sulfur → H2S, nitrogen → NH3, metals deposit on the catalyst",
b:"Hydrotreating is the most widespread process in modern refining. Almost every product stream gets hydrotreated before leaving the refinery. Petroleum fractions pass over a catalyst in the presence of hydrogen at moderate pressure. Sulfur atoms are stripped from hydrocarbon molecules and combine with hydrogen to form H2S gas. Nitrogen forms NH3. Metals deposit on the catalyst. The clean product moves on.",
x:"Environmental regulations have driven massive expansion of hydrotreating. US highway diesel went from 5,000 ppm sulfur to just 15 ppm (Ultra-Low Sulfur Diesel, ULSD). This required enormous investment in hydrotreating capacity and hydrogen production. Naphtha must also be hydrotreated before reforming because sulfur poisons the expensive platinum catalyst."},
{t:"The Hydrogen Balance",h:"Reformer makes it, hydrotreaters and hydrocrackers consume it - balance is critical",
b:"Hydrogen supply: mainly the catalytic reformer, producing 1,000-2,000 scf H2 per barrel of naphtha feed. Hydrogen demand: all hydrotreaters (naphtha, kerosene, diesel, gas oil) plus the hydrocracker. If demand exceeds supply, a Steam Methane Reformer (SMR) makes more: CH4 + H2O → CO + 3H2. SMR hydrogen is expensive, so the refinery optimizes to minimize the need for it.",
x:"The hydrogen balance is like a refinery's budget - every unit that produces H2 is an income stream, every consumer is an expense. When environmental regulations tighten sulfur limits, hydrogen 'expenses' go up, potentially requiring capital investment in new SMR capacity."},
{t:"Sulfur Recovery: The Claus Process",h:"Turn H2S pollution into solid yellow sulfur you can sell by the truckload",
b:"All the H2S generated by hydrotreating is sent to the Claus plant. The reaction: 2H2S + SO2 → 3S + 2H2O (elemental sulfur + water). The sulfur is recovered as a yellow liquid, cooled to solid form, and sold as a commodity. Recovery efficiency: 95-97%. Tail gas treatment catches most of the rest. A typical refinery produces 100+ tons per day of sulfur, sold for fertilizer manufacturing, rubber vulcanization, and chemical production.",
x:"Before environmental regulations, many refineries simply burned H2S in their flares, releasing SO2 into the atmosphere. The Claus process turned a pollution problem into a revenue stream - the sulfur has real commercial value."}
],
quiz:[
{q:"US highway diesel sulfur content went from ___ to ___ due to regulations:",o:["500 ppm to 50 ppm","5,000 ppm to 15 ppm","1% to 0.5%","10,000 ppm to 100 ppm"],c:1,e:"Ultra-Low Sulfur Diesel (ULSD) regulations required diesel sulfur to drop from 5,000 ppm to just 15 ppm - a 99.7% reduction requiring massive hydrotreating investment."},
{q:"In hydrotreating, sulfur in the feed is converted to:",o:["SO2 gas released to atmosphere","H2S gas (which goes to sulfur recovery)","Solid sulfur deposited on the catalyst","Sulfuric acid"],c:1,e:"Sulfur atoms are stripped from hydrocarbons and combine with hydrogen to form H2S gas. The H2S is then sent to the Claus plant for conversion to solid elemental sulfur."},
{q:"If the refinery's hydrogen demand exceeds what the reformer produces, the shortfall is made up by:",o:["Buying crude with more hydrogen","A Steam Methane Reformer (CH4 + H2O → CO + 3H2)","Importing hydrogen from natural gas plants","Reducing hydrotreating - letting sulfur through"],c:1,e:"A Steam Methane Reformer (SMR) converts natural gas (methane) and steam into hydrogen and CO. It's effective but expensive to build and operate."},
{q:"The Claus process converts H2S into:",o:["Sulfuric acid","SO2 for the atmosphere","Solid elemental sulfur (sellable commodity)","Hydrogen"],c:2,e:"Claus converts H2S into solid yellow sulfur and water (2H2S + SO2 → 3S + 2H2O). The sulfur is sold for fertilizer, rubber, and chemicals - turning pollution into profit."}
]},

{id:16,n:"XVI",t:"Isomerization",d:"Same formula, new shape, dramatically higher octane",
concepts:[
{t:"Converting Straight Chains to Branched Chains",h:"N-pentane: 62 RON → Isopentane: 93 RON. Same C5H12!",
b:"Isomerization converts straight-chain (normal) paraffins to their branched (iso) forms using a platinum catalyst with a chloride promoter. The most common application: converting n-pentane (62 RON) and n-hexane to isopentane (~93 RON) and isohexane for gasoline blending. Also converts n-butane to isobutane when the gas plant can't supply enough isobutane for alkylation.",
x:"The reaction is an equilibrium: about 60% conversion per pass. Unconverted normal paraffin is separated and recycled. The process conditions are relatively mild compared to reforming - lower temperatures (200-400°F) and moderate pressures. It's a simple, reliable octane upgrade."},
{t:"Butane Isomerization for Alkylation Feed",h:"When the gas plant can't supply enough isobutane, isomerize normal butane",
b:"The alkylation unit's appetite for isobutane often exceeds what the gas plant separates from refinery gas streams. The solution: run excess normal butane through a butane isomerization unit. Some normal butane is also consumed as gasoline blendstock, so there's competition for this molecule between isomerization, gasoline blending, and petrochemical use.",
x:"The interplay is: cat cracker makes olefins → olefins need isobutane for alkylation → not enough isobutane from gas plant → isomerize normal butane to isobutane. Each unit's demand ripples through the refinery system."}
],
quiz:[
{q:"Isomerization converts n-pentane (62 RON) to isopentane with a RON of approximately:",o:["65","75","93","100"],c:2,e:"Isopentane has ~93 RON compared to n-pentane's 62 RON. Same C5H12 formula, but the branched structure dramatically resists knocking in engines."},
{q:"The isomerization reaction achieves about ___ conversion per pass:",o:["10%","30%","60%","99%"],c:2,e:"Isomerization is an equilibrium reaction achieving about 60% conversion per pass. Unconverted normal paraffin is separated and recycled through the reactor."},
{q:"Butane isomerization exists primarily to:",o:["Make better gasoline directly","Supply isobutane to the alkylation unit when the gas plant can't provide enough","Remove sulfur from butane","Convert butane to propane"],c:1,e:"When alkylation demand for isobutane exceeds gas plant supply, normal butane is isomerized to isobutane to fill the gap."}
]},

{id:17,n:"XVII",t:"Solvent Recovery of Aromatics",d:"Extracting BTX chemicals from reformate for the petrochemical industry",
concepts:[
{t:"BTX: More Valuable as Chemicals Than as Gasoline",h:"Benzene → nylon, plastics. Toluene → solvents, polyurethane. Xylene → PET bottles, polyester.",
b:"Reformate from the catalytic reformer is rich in aromatics: benzene (C6H6), toluene (C7H8), and xylene (C8H10) - collectively BTX. These can be sold to petrochemical companies at premium prices rather than being left in gasoline. A polar solvent (sulfolane or glycol) selectively dissolves the aromatics from the reformate, leaving the non-aromatic paraffins and naphthenes behind.",
x:"The extraction exploits polarity: aromatic rings are slightly polar and dissolve preferentially in polar solvents. Paraffins and naphthenes are non-polar and stay behind. After extraction, the aromatics are recovered from the solvent by distillation. It's a physical separation, not a chemical reaction."},
{t:"Individual Aromatic Products",h:"Each one feeds a different chemical chain worth billions",
b:"Benzene → styrene (polystyrene foam, ABS plastics), cyclohexane (nylon), phenol (epoxy resins). Toluene → polyurethane intermediates, solvents, TNT. Xylene (specifically para-xylene) → PET plastic (water bottles, food containers) and polyester fiber (clothing). These chemical applications typically pay more than the fuel value of the same molecules.",
x:"Whether a refiner extracts aromatics or leaves them in gasoline depends on the relative economics. When petrochemical margins are strong, more aromatics are extracted. When gasoline margins are high or the refinery lacks extraction equipment, they stay in gasoline as high-octane blending components."}
],
quiz:[
{q:"BTX stands for:",o:["Butane, Toluene, Xanthene","Benzene, Toluene, Xylene","Base, Top, Xtract","British Thermal eXchange"],c:1,e:"BTX = Benzene, Toluene, Xylene - the three most important aromatic hydrocarbons, extracted from reformate for petrochemical use."},
{q:"Para-xylene is the starting material for:",o:["Gasoline additives","Asphalt","PET plastic (water bottles) and polyester fiber","Lubricating oil"],c:2,e:"Para-xylene is converted to PTA (purified terephthalic acid), which becomes PET plastic for bottles and packaging, and polyester fiber for textiles."},
{q:"The solvent extraction process works because:",o:["Aromatics are heavier than paraffins","Aromatics are slightly polar and dissolve preferentially in polar solvents","Aromatics boil at higher temperatures","Aromatics are radioactive"],c:1,e:"Aromatic rings have slight polarity due to their electron structure. Polar solvents like sulfolane dissolve them preferentially while non-polar paraffins remain behind."}
]},

{id:18,n:"XVIII",t:"Ethylene Plants",d:"Steam cracking to make the world's most produced organic chemical",
concepts:[
{t:"Ethylene: The Foundation of Modern Plastics",h:"200+ million tons per year. Polyethylene bags, PVC pipes, antifreeze - it all starts with C2H4.",
b:"Ethylene (C2H4) is the world's most produced organic chemical. It's made by steam cracking: hydrocarbon feed (ethane, naphtha, or gas oil) mixed with steam is heated to ~1,500°F in furnace tubes for a residence time of only 0.1-0.5 seconds. Then it's IMMEDIATELY quenched (rapidly cooled) to freeze the product composition.",
x:"The rapid quench is critical. At 1,500°F, the thermodynamics favor ethylene formation. But if the products aren't cooled instantly, they continue reacting into heavier, less valuable molecules and eventually coke. It's like pulling bread from the oven at exactly the right moment - leave it too long and it burns."},
{t:"Feedstock Flexibility and Co-products",h:"Crack ethane for maximum ethylene, or crack naphtha for a broader product mix",
b:"Different feedstocks give different product slates. Ethane cracking yields mostly ethylene (high selectivity). Naphtha cracking produces ethylene plus significant amounts of propylene, butadiene, butylenes, and aromatics (benzene, toluene). Gas oil cracking produces even more co-products but at lower ethylene selectivity. The choice depends on feedstock availability and the value of co-products.",
x:"US crackers predominantly use ethane (cheap from shale gas). European and Asian crackers use more naphtha. Middle Eastern crackers use ethane from associated gas. Each region's feedstock economics determine the optimal configuration."}
],
quiz:[
{q:"Residence time in the steam cracking furnace is:",o:["Several hours","About 30 minutes","Only 0.1-0.5 seconds","About 10 minutes"],c:2,e:"The feed is in the furnace for only fractions of a second. Any longer and the desired ethylene continues reacting into heavier, less valuable byproducts."},
{q:"Why is immediate quenching (rapid cooling) critical after steam cracking?",o:["To save energy","The products would explode if not cooled","Hot products continue reacting into unwanted heavy molecules and coke if not frozen quickly","The equipment can't handle sustained high temperatures"],c:2,e:"At 1,500°F, the right product mix forms quickly. Without immediate quenching, the products keep reacting, forming heavier molecules and coke rather than the desired ethylene."},
{q:"US ethylene crackers predominantly use ___ as feedstock:",o:["Naphtha","Gas oil","Ethane (from shale gas)","Crude oil"],c:2,e:"Abundant, cheap ethane from US shale gas production has made ethane the preferred feedstock for US ethylene plants, giving high ethylene selectivity at low cost."}
]},

{id:19,n:"XIX",t:"Simple & Complex Refineries",d:"The capstone chapter - how all the units fit together and why complexity equals profitability",
concepts:[
{t:"The Hydroskimming (Simple) Refinery",h:"Just a crude unit, reformer, and treaters. Complexity index ~2.5. Limited and vulnerable.",
b:"A hydroskimming refinery has only: crude distilling, gas plant, naphtha splitter, catalytic reformer, and hydrotreaters for naphtha, kerosene, and distillate. It can separate crude into fractions and upgrade naphtha octane, but it CANNOT convert heavy products to lighter ones. It produces a large percentage of residual fuel oil. Complexity calculation: crude unit (1.0×1.0=1.0) + gas plant (0.5×0.5=0.25) + reformer (4.0×0.15=0.6) + treaters ≈ 2.5 total.",
x:"A simple refinery is at the mercy of crude quality. Process heavy crude and you get mostly low-value residual fuel. Only light, sweet crudes produce acceptable product slates. This limits crude purchasing flexibility and profitability."},
{t:"The Complex (Conversion) Refinery",h:"Add a flasher, cat cracker, hydrocracker, coker, alky unit - complexity 8-14+",
b:"A complex refinery adds conversion units: vacuum flasher (2.0), cat cracker (6.0), hydrocracker (10.0), alkylation (11.0), coker (6.0), plus auxiliary treaters. These convert heavy, low-value products into gasoline, diesel, and jet fuel. Total complexity rises to 8-14+. The investment is enormous but pays for itself through the ability to process cheap, heavy, sour crude and still produce premium products.",
x:"Example: a complex refinery might buy heavy sour crude at $5-15/bbl less than light sweet crude, but produce essentially the same slate of finished products. On 200,000 bbl/day, that's $1-3 million per day in crude cost savings. Even massive capital investment in conversion units pays back quickly at those numbers."},
{t:"The Nelson Complexity Index",h:"One number that captures a refinery's capability - crude unit = 1.0, everything else is relative",
b:"Developed by Wilbur Nelson, this index measures refinery sophistication. Each unit type has a complexity factor reflecting its cost relative to crude distilling: crude unit = 1.0, vacuum flasher = 2.0, cat reformer = 4.0, cat cracker = 6.0, coker = 6.0, hydrocracker = 10.0, alkylation = 11.0. Multiply each factor by the unit's throughput as a fraction of crude capacity, then sum all values.",
x:"Global benchmarking: the most complex refineries in the world (Jamnagar in India, Ulsan in South Korea) have complexity indices above 12-14. Simple European refineries might be 5-6. Higher complexity correlates with higher profitability and ability to process a wider range of crudes."},
{t:"Why Complexity = Profitability",h:"The margin is captured in the spread between cheap crude and expensive products",
b:"Complex refineries capture margin in two ways: (1) Buy cheaper, heavier crude because they can upgrade it. (2) Produce more high-value products (gasoline, diesel, jet) and less low-value residual fuel from any crude. The 'gross refining margin' (value of products minus cost of crude and utilities) is consistently higher for complex refineries across all market conditions.",
x:"During periods of wide crude quality differentials (light-heavy spread), complex refineries earn outsized profits. During narrow spreads, they still outperform simple refineries. The investment in complexity provides structural competitive advantage."}
],
quiz:[
{q:"A hydroskimming refinery's main limitation is:",o:["It uses too much energy","It can only separate crude, not convert heavy fractions to lighter products","It produces too much gasoline","It's too expensive to build"],c:1,e:"A simple refinery lacks conversion units. It can't turn heavy residue into gasoline or diesel. Processing heavy crude yields mostly low-value residual fuel oil."},
{q:"The Nelson Complexity Index of a crude distilling unit is:",o:["0","1.0 (the baseline)","5.0","10.0"],c:1,e:"The crude distilling unit is defined as the baseline at 1.0. All other units are measured relative to it. A reformer is 4.0, a cat cracker 6.0, a hydrocracker 10.0."},
{q:"Which unit has the HIGHEST Nelson complexity factor?",o:["Crude unit (1.0)","Cat cracker (6.0)","Hydrocracker (10.0)","Alkylation (11.0)"],c:3,e:"Alkylation has the highest complexity factor at 11.0, reflecting its expensive acid handling equipment and the premium value of its alkylate product."},
{q:"A complex refinery's key economic advantage is:",o:["Lower energy costs","Ability to buy cheap heavy/sour crude and produce the same premium products as a simple refinery running expensive light crude","Simpler operations","Fewer environmental regulations"],c:1,e:"The heavy-light crude price differential can be $5-15/bbl. On 200,000 bbl/day, that's $1-3 million/day in crude cost savings - more than justifying the conversion unit investment."},
{q:"A refinery with a complexity index of ~2.5 is:",o:["A full conversion refinery","A petrochemical complex","A hydroskimming (simple) refinery","A topping unit only"],c:2,e:"Complexity of ~2.5 = hydroskimming refinery with crude unit, gas plant, reformer, and treaters. No conversion units. The simplest commercial refinery configuration."}
]},

{id:20,n:"XX",t:"Crude Oil, Condensate & NGL",d:"Not all liquid hydrocarbons are crude oil - know the differences",
concepts:[
{t:"Three Types of Liquid Hydrocarbons",h:"Crude oil from oil wells, condensate from gas wells, NGL from gas plants",
b:"Crude oil comes directly from oil wells. Condensate is very light liquid (50-60+ API) that condenses from natural gas as temperature and pressure drop at the surface. Natural Gas Liquids (NGLs) are ethane, propane, butanes, and natural gasoline extracted from natural gas streams at gas processing plants. Each has different properties, different values, and different optimal processing paths.",
x:"Condensates are so light they yield mostly gasoline and naphtha with very little heavy material. They can supplement crude in refineries designed for light feeds, but may actually cause problems in complex refineries designed for heavier crude (not enough heavy feed for the conversion units)."},
{t:"Crude Oil Pricing and Quality",h:"Benchmarks, differentials, and why some crudes cost $10+ less per barrel than others",
b:"Crude oil is priced relative to benchmarks: WTI (West Texas Intermediate) in the US, Brent in Europe, Dubai/Oman in Asia. Each crude trades at a premium or discount to the benchmark based on its API gravity and sulfur content. Light sweet crudes like Bonny Light (Nigeria) trade at premiums. Heavy sour crudes like Maya (Mexico) or Arab Heavy trade at discounts. The discount reflects the higher processing cost and lower product value.",
x:"Complex refineries specifically target discounted heavy/sour crudes because their conversion units can upgrade the heavy material. The wider the light-heavy differential, the more a complex refinery earns. This is why refinery configuration and crude selection must be optimized together."}
],
quiz:[
{q:"Condensate differs from crude oil because:",o:["It's heavier and has more sulfur","It's very light (50-60+ API) liquid that condenses from natural gas at the surface","It's always sour","It comes only from offshore wells"],c:1,e:"Condensate is very light liquid that drops out of natural gas as temperature and pressure decrease. At 50-60+ API, it yields mostly naphtha and gasoline."},
{q:"Why do heavy sour crudes sell at a discount?",o:["They're from unstable regions","They yield less valuable products and require more expensive processing (conversion + desulfurization)","They're harder to transport","They taste sour"],c:1,e:"Heavy crude yields more low-value residue and less gasoline. Sour crude requires costly desulfurization. Refiners won't pay the same price for crude that costs more to process and yields less valuable products."}
]},

{id:21,n:"XXI",t:"Fuel Values & Heating Values",d:"How much energy is actually in each petroleum product - measured in BTUs",
concepts:[
{t:"The BTU: Universal Energy Currency",h:"1 BTU = energy to heat 1 pound of water by 1°F. Every fuel decision comes down to BTUs per dollar.",
b:"A British Thermal Unit (BTU) is the energy needed to raise 1 pound of water by 1°F. Typical values: natural gas ~1,000 BTU/cubic foot, gasoline ~125,000 BTU/gallon, diesel ~140,000 BTU/gallon, residual fuel ~150,000 BTU/gallon. Heavier fuels generally contain more BTUs per gallon (they're denser, so more mass per gallon) but fewer BTUs per pound (they burn slightly less completely).",
x:"BTU-based comparisons drive fuel switching decisions. If natural gas costs $3/million BTU and residual fuel oil costs $5/million BTU equivalent, power plants switch to natural gas. These calculations happen constantly in industrial and utility settings, shifting demand between fuels and affecting refinery economics."},
{t:"Fuel Equivalencies and Economics",h:"Comparing fuels on an energy basis reveals which is truly cheapest",
b:"Since different fuels have different energy densities, a gallon of diesel provides more energy than a gallon of gasoline. A barrel of residual fuel provides more BTUs than a barrel of diesel. To fairly compare fuel costs, you must calculate the cost per million BTU (or per gigajoule internationally). This 'energy-equivalent' pricing drives decisions about which fuel to use in power plants, ships, and industrial boilers.",
x:"This is why diesel vehicles get better fuel mileage than gasoline vehicles (aside from engine efficiency differences) - each gallon of diesel contains about 12% more energy than a gallon of gasoline. When fuel prices are similar per gallon, diesel is actually cheaper per mile driven."}
],
quiz:[
{q:"One BTU is defined as:",o:["The energy in one barrel of crude","The energy to heat 1 pound of water by 1°F","The energy output of one refinery furnace per hour","1,000 calories"],c:1,e:"BTU = British Thermal Unit: the energy needed to raise the temperature of 1 pound of water by 1 degree Fahrenheit. It's the standard energy measure in the petroleum industry."},
{q:"Diesel has ~140,000 BTU/gallon while gasoline has ~125,000 BTU/gallon. This means:",o:["Gasoline is more energy-dense","Diesel provides about 12% more energy per gallon (partly explaining better diesel fuel economy)","They have equal energy content","Gasoline engines are more efficient"],c:1,e:"Diesel is denser and contains more energy per gallon. This energy density difference (plus diesel engine efficiency advantages) explains why diesel vehicles typically achieve better fuel economy."},
{q:"When comparing fuel costs, the most meaningful metric is:",o:["Price per gallon","Price per barrel","Cost per million BTU (energy-equivalent pricing)","Price per pound"],c:2,e:"Cost per million BTU allows apples-to-apples comparison between fuels with different energy densities. A gallon of diesel and a gallon of gasoline contain different amounts of energy, so price per gallon doesn't tell the full story."}
]}
];

// ===================== BADGE DEFINITIONS =====================
const badgeDefs = [
{id:"first",i:"\u{1F476}",n:"First Step",d:"Complete your first chapter"},
{id:"ace",i:"\u{1F3C6}",n:"Quiz Ace",d:"Score 100% on any quiz"},
{id:"half",i:"\u{1F334}",n:"Halfway There",d:"Complete 10 chapters"},
{id:"scholar",i:"\u{1F393}",n:"Scholar",d:"Complete all 21 chapters"},
{id:"s3",i:"\u{1F525}",n:"On Fire",d:"3-chapter streak"},
{id:"s5",i:"\u26A1",n:"Unstoppable",d:"5-chapter streak"},
{id:"x500",i:"\u{1F4B0}",n:"XP Hunter",d:"Earn 500 total XP"},
{id:"x1k",i:"\u{1F48E}",n:"XP Legend",d:"Earn 1000 total XP"},
{id:"speed",i:"\u23F1",n:"Speedster",d:"Complete a quiz in under 30 seconds"},
{id:"owl",i:"\u{1F989}",n:"Night Owl",d:"Study after 10 PM"}
];
